/:
  controller: Main
  action: home

/page:
  controller: Page
  action: show

/register:
  controller: User
  action: register
  methods: [GET, POST]

/login:
  controller: User
  action: login
  methods: [GET, POST]

/logout:
  controller: User
  action: logout
  methods: [GET]

/dashboard:
  controller: Backoffice
  action: dashboard
